// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";
import "dotenv/config";

// FIX?: Error: P1013: The provided database string is invalid.
// Ambil URL asli
const rawUrl = env('DATABASE_URL') || "file:./db.sqlite";

// TRICK: Prisma CLI (Rust) hanya mau menerima 'file:' atau 'sqlite:' 
// Kita ubah libsql:// menjadi file: hanya untuk CLI agar tidak error P1013
// const cliUrl = rawUrl.replace("libsql://", "file:");

// console.log("CLI Connection URL:", cliUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: rawUrl,
  },
});
